.circleci/config.yml, .gitignore, package.json, tsconfig.json, tsconfig.node.json, utils/netlify-deploy.ts, utils/typings/netlify/index.d.ts, yarn.lock
This PR enables Netlify preview deploys 🎉
I've added the `ts-node` library to allow us to create any node utilities with TypeScript and the same process as our React code.
The deploy preview process is roughly:
1. Ensure all environment variables are available for the script
2. Determine the environment (`production` vs `preview`) based off of the branch name
3. Create a new Github deploy for the current commit
4. Deploy the site to Netlify depending on the environment above
5. Create a new Github deployment status using the deploy URL provided from Netlify
=> Add netlify preview deployments

gatsby-config.js, plugins/gatsby-source-abstract/gatsby-node.js, src/pages/content/index.mdx
It looks like our `abstract-sdk` bug was fixed sometime recently. To properly show Abstract Assets I've removed our filtering logic.
=> fix: update gatsby-source-abstract filter logic

src/examples/design/icons/SvgSearch.tsx, src/layouts/Titled/components/TOC.tsx, src/nav/design.yml, src/pages/design/icons/12.mdx, src/pages/design/icons/16.mdx, src/pages/design/icons/26.mdx, src/pages/design/icons/installation.mdx, src/pages/design/icons/wordmarks.mdx, src/pages/design/index.mdx
Took a little time yesterday to get to the know the budding site structure a little better. This PR has some IA structure updates and then in lieu of a proper design spec for the icon pages, made a few small column and alignment adjustments for legibility.
=> fix: initial icon IA updates/styling

gatsby-config.js, plugins/gatsby-source-abstract/gatsby-node.js
The previous code timing prevents `.env` token from being passed to Abstract.
=> fix: move token validation and dotenv to the top of gastby config

src/pages/design/icons/12.mdx, src/pages/design/icons/16.mdx, src/pages/design/icons/26.mdx
This pull request sorts the SVG icons by name in ascending order by passing a sort option into the GraphQL query.
=> fix: sort icons by name in ascending order

src/components/MarkdownProvider/components/BestPractice.tsx, src/components/MarkdownProvider/components/Usage.tsx, src/components/MarkdownProvider/index.tsx, src/layouts/Titled/index.tsx, src/pages/components/avatar.mdx, src/pages/design/index.mdx
Addressed a variety of layout bugs, simplified grid usage (no `flex-direction: column`), and rebuilt the `BestPractice` component.
In **draft** mode as one-off visuals can be found on the `/design` page. @rossmoody let me know if you want me to keep these for now or dispose before I open up for non-draft review. 🙏 
...with added support for:
=> chore(components): refine BestPractice component

package.json, src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts, src/examples/breadcrumbs/BreadcrumbsDefault.tsx, src/nav/components.yml, src/pages/components/breadcrumbs.mdx, yarn.lock
This pull request introduces the `Breadcrumb` Component Page. Use the View deployment button further down this page to view a build of this Pull Request.
=> feat: add breadcrumbs component page

plugins/gatsby-source-react-packages/gatsby-node.js, src/components/MarkdownProvider/components/Configuration.tsx, src/components/MarkdownProvider/components/PackageDescription.tsx, src/components/MarkdownProvider/components/PropSheets.tsx, src/components/MarkdownProvider/index.tsx, src/pages/components/anchor.mdx, src/pages/components/avatar.mdx, src/pages/components/breadcrumbs.mdx, src/pages/components/button.mdx, src/pages/index.tsx
This PR introduces the configuration section styling and logic into the component pages. 
1. The `UnorderedList.Item` component renders a wrapping child div. Instead of creating an additional wrapping element for Flex styling, we styled the child div with Flex styles using `& > div` CSS selector
1. The Configuration and API section props and component names were getting a little confusing. The names were revised a bit to [more accurately reflect what they are for.](https://github.com/zendeskgarden/website/compare/rmoody/configuration?expand=1#diff-0b9a85d38fa919055fd1752418521e3aR85)
=> feat(components): add configuration section

content/news/news.yml, src/layouts/Home/components/News.tsx, src/layouts/Home/components/Search.tsx, src/layouts/Home/index.tsx, src/layouts/Root/components/Footer.tsx, src/layouts/Root/components/Header.tsx, src/layouts/Root/components/StyledNavigationLink.tsx, src/layouts/Sidebar/components/MobileSidebar.tsx, src/nav/components.yml, src/nav/design.yml, src/pages/components/autocomplete.mdx, src/pages/components/button-group.mdx, src/pages/components/checkbox.mdx, src/pages/components/icon-button.mdx, src/pages/components/menu.mdx, src/pages/components/radio.mdx, src/pages/components/range.mdx, src/pages/components/split-button.mdx, src/pages/components/text-input.mdx, src/pages/components/toggle.mdx, src/pages/components/typography.mdx, src/pages/components/versions.mdx
This PR aims to have every link on the site that is to be in the MVP represented and with a legitimate endpoint (whether on this site or the old). 
1. I had to write a little logic to get the sidebar links to style and function correctly depending on whether they are an `<a>` or a Gatsby Link. Gatsby `<Link>` components only allow for internal linking. Very open to feedback on that implementation as it was a smidge outside my comfort zone (especially the types). 
2. On the homepage I omitted the "Site news" section as that won't be represented.
4. Pages that are for on the MVP site but aren't ready yet I created blank placeholder pages. 
5. I think the Content section is still set to be revised a little depending on @vsri1137 direction, but it's pretty close.
6. I created a Versions page …
=> chore: information architecture links

package.json, src/components/MarkdownProvider/components/Markdown.tsx, src/components/MarkdownProvider/components/PropSheets.tsx, src/components/MarkdownProvider/index.tsx, src/pages/design/index.mdx, utils/typings/remark-react.d.ts, yarn.lock
Used to apply component-internal markdown styling for text that is out-of-scope for MDX.
PR demonstrates usage within prop sheets.
=> feat: add new <Markdown> component

src/components/MarkdownProvider/components/OverviewLinks.tsx, src/components/MarkdownProvider/index.tsx, src/pages/components/index.mdx, src/pages/content/index.mdx, src/pages/design/index.mdx
This is an approach for the temporary overview page links to address navigating when the sidebar disappears. I was thinking that borrowing a similar approach from the sidebar navigation for the overview pages might be nice for programmatically showing the correct links in each section. This way we don't have to manually keep track of IA changes on each overview page.
=> chore: overview links

src/pages/components/anchor.mdx, src/pages/components/breadcrumbs.mdx, src/pages/components/button.mdx, src/pages/components/inputs.mdx, src/pages/components/menu.mdx, src/pages/components/multiselect.mdx, src/pages/components/select.mdx, src/pages/components/tabs.mdx
This PR contains two updates: 
1. It revises the headline `Examples` to `How to use it` across all component pages so we don't accidentally miss one. 
2. Updates the copy on Breadcrumbs to new UXCS approved copy.
=> chore: update breadcrumb copy

src/examples/forms/radio/Default.tsx, src/examples/forms/radio/Disabled.tsx, src/examples/forms/radio/Hidden.tsx, src/examples/forms/radio/Hint.tsx, src/examples/forms/radio/RegularWeightLabel.tsx, src/examples/forms/radio/Validation.tsx, src/pages/components/radio.mdx
This PR introduces the Radio component page.
=> feat: add radio component page

src/components/MarkdownProvider/components/CodeExample/index.tsx, src/layouts/Root/components/Header.tsx, src/layouts/Root/index.tsx, src/layouts/Titled/components/TOC.tsx
Update code example button tooltip copy per design feedback.
The `Toast` notifications for copy/copied will be done in a follow-on PR.
=> fix(examples): static copy for code icon button tooltips

src/examples/button/ButtonGroupSize.tsx, src/examples/button/ButtonGroupType.tsx, src/pages/components/button-group.mdx
This PR introduces the `<ButtonGroup>` component to the website.
=> feat: add button group component

src/examples/button/IconButtonDanger.tsx, src/examples/button/IconButtonDisabled.tsx, src/examples/button/IconButtonShapes.tsx, src/examples/button/IconButtonSizes.tsx, src/examples/button/IconButtonTypes.tsx
This PR introduces a fix to the icon size in the examples of `IconButton` components from 26 to 16 to match the current Garden site implementation.
=> fix: revise icon button icon size

src/examples/dropdowns/autocomplete/Default.tsx, src/examples/dropdowns/autocomplete/Media.tsx, src/examples/dropdowns/autocomplete/Size.tsx, src/pages/components/autocomplete.mdx
This PR introduces the Autocomplete component page.
=> feat: add autocomplete component page

src/examples/button/IconButtonDanger.tsx, src/examples/button/IconButtonDisabled.tsx, src/examples/button/IconButtonShapes.tsx, src/examples/button/IconButtonSizes.tsx, src/examples/button/IconButtonTypes.tsx, src/examples/button/SplitButtonSizes.tsx, src/examples/button/SplitButtonTypes.tsx, src/examples/dropdowns/menu/Arrow.tsx, src/examples/dropdowns/menu/Button.tsx, src/examples/dropdowns/menu/Disabled.tsx, src/examples/dropdowns/menu/Media.tsx, src/examples/dropdowns/menu/Meta.tsx, src/examples/dropdowns/menu/Nested.tsx, src/examples/dropdowns/menu/Placement.tsx, src/examples/dropdowns/menu/Size.tsx, src/pages/components/menu.mdx
- Unless icon buttons have a tooltip, they should include an `aria-label`.
- Update split button examples to incorporate chevron rotation.
- Improve split button menu placement (should be `bottom-end`).
- Update menu examples to use chevron media buttons.
- Update menu-arrow example to use an icon button trigger.
- Add `Dropdown` prop sheet to the Menu component page.
=> fix(examples): menu and icon buttons

src/layouts/Home/components/News.tsx
Somewhere along recent commits, the `z-index` for the 50/50 news panels got altered so they were covering the content. This PR removes those as they are not currently relevant for the design.
=> fix(home): restore hidden news section

gatsby-config.js, src/components/MarkdownProvider/components/BestPractice.tsx, src/layouts/Home/components/Foundation.tsx, src/layouts/Home/components/Search.tsx, src/pages/components/autocomplete.mdx, src/pages/components/avatar.mdx, src/pages/components/checkbox.mdx, src/pages/components/icon-button.mdx
- Bump `defaultQuality` for `gatsby-plugin-sharp` to 90
- Allow `BestPractice` component to receive a `FluidObject` for `<Img>` rendering
- Clear unnecessary `alt` tags
- Improve SVG tracing for home page navigation graphics
Refer to internal channel 🧵  for image quality notes.
=> fix: image quality and sizing

src/examples/dropdowns/autocomplete/Size.tsx, src/examples/dropdowns/multiselect/Size.tsx
This PR updates the Autocomplete and Multiselect to use individual component state so that interaction with one component does not affect the other.
❌  **before (autocomplete)**: selecting one autocomplete affects the other
✅ **after (autocomplete)**: selecting one autocomplete does not affects the other
❌ **before (multiselect)**: interacting with one multiselect affects the other
✅ **after (multiselect)**: interacting with one multiselect does not affects the other
=> fix(examples): update dropdown size examples to use separate state

src/examples/avatar/AvatarType.tsx
The image in the Avatar types CodeSandbox example is broken because CodeSandbox cannot resolve the relative path to the image. This PR proposes using the URL from the published site. @jzempel @austin94 does a better solution than this come to mind? Open to suggestions.
❌ **before**:
✅ **after**:
=> fix(avatar): fix image in codesandbox example

src/components/MarkdownProvider/components/OverviewLinks.tsx
The lists used to render overview links were invalid because they contained a nested `ul` element. 
This PR removes the unnecessary nested `ul` within a `ul` and ensures that `ul` elements only have `li` elements as its children.
=> fix: remove duplicate unordered list 

src/layouts/Home/components/SectionCallout.tsx
This pull request fixes failing contrast ratios for:
* Home page section headers "_FOUNDATION_", "_CONTENT_", "_DESIGN_", and "_COMPONENTS_" 
* Component pages that include a "_Table of Contents_" section header 
❌ **before: 3.17 failing contrast ratio**
✅ **after: 4.84 passing contrast ratio**
=> fix: failing contrast ratios

src/pages/components/input.mdx
Add missing link for Textarea on Inputs component page.
=> fix: link to textarea on forms component page

src/examples/typography/CodeColor.tsx, src/examples/typography/CodeSize.tsx, src/examples/typography/ListSize.tsx, src/examples/typography/Lists.tsx, src/examples/typography/TypeScale.tsx, src/pages/components/typography.mdx
When building out the Typography component page @allisonacs noticed that some examples (Lists and Code highlight) [weren't clear](https://github.com/zendeskgarden/website/pull/100#pullrequestreview-446058820). 
This PR updates the copy and adds examples which clearly demonstrate the following:
1) Types of lists, e.g. ordered vs unordered
2) List sizes
3) Code highlight background colors
4) Code highlight sizes
=> chore: update typography examples

src/layouts/Root/index.tsx, src/layouts/Titled/components/TOC.tsx
Users should be able to scroll through the Table of Contents (on Desktop sizes) with lots of content (e.g. [Word List](https://zendeskgarden.netlify.app/content/word-list)). This PR updates the `TOC` component so that long Tabe of Contents can be scrolled.
=> fix: allow table of contents to scroll

src/components/MarkdownProvider/components/CodeExample/index.tsx, src/components/SEO.tsx
- Set favicon URLs so that they continue to work on non-root pages
- Fix code example tool container bottom `border-radius` to prevent over-bleed
=> fix: favicons and code example tools container

gatsby-config.js, src/examples/avatar/AvatarType.tsx
Setup for garden.zendesk.com DNS update. A merge will break a couple image URLs for `zendeskgarden.netlify.app` but will prepare the site to be ready for TTL.
- updates the siteUrl used for `og:image` social sharing
- updates avatar img to source from the new location
=> chore: update subdomain URLs

src/components/MarkdownProvider/components/BestPractice.tsx, src/layouts/Home/components/Foundation.tsx, src/layouts/Home/components/Patterns.tsx, src/layouts/Home/components/Search.tsx, src/layouts/Root/components/Footer.tsx, src/layouts/Root/components/Header.tsx, src/layouts/Sidebar/components/DesktopSidebar.tsx, src/layouts/Sidebar/components/MobileSidebar.tsx, src/layouts/Sidebar/index.tsx, src/layouts/Titled/index.tsx, src/pages/404.tsx, src/temp/mediaQuery.ts
Since `@media` queries in CSS are by definition inclusive, all `max-width` queries need to bump slightly (`.02px`) down from the top-end breakpoint in order to play nicely with corresponding `min-width` queries.
For review:
- all `max-width` media queries get replaced with `mediaQuery('down', size /* key is one less */)`
- all `min-width` media queries get replaced with `mediaQuery('up', size /* key is equal */)`
The `mediaQuery` utility added to this PR is a **temporary** solution to be deleted and replaced by `import { mediaQuery } from @zendeskgarden/react-theming` once https://github.com/zendeskgarden/react-components/pull/814 is merged and a new feature release of `react-components` is available.
At that time, we'll continue to sweep through and replace all `@media` queries within …
=> fix: @media queries

package.json, yarn.lock
Need to manually update until an automated process is in place for keeping components fresh.
=> chore: update svg-icons to v6.20.0

src/components/MarkdownProvider/components/OverviewLinks.tsx
Current `Overview` link that reloads the Overview page is confusing to users. Skip past rendering the first item in the navigation list.
**Before**
**After**
=> fix: skip past Overview link-to-self

gatsby-config.js, src/components/MarkdownProvider/components/Anchor.ts, src/components/MarkdownProvider/components/Markdown.tsx, src/components/MarkdownProvider/components/Typography.tsx, src/components/MarkdownProvider/index.tsx
This PR addresses the following issues with [autolink](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/) header styling:
- pull the (previously outdated) link icon directly from the `svg-icons` package
- replace [`GlobalStyle`](https://styled-components.com/docs/api#createglobalstyle) with more predictable extension of the Garden `Anchor` component
- improve CSS by manipulating `color` instead of `visibility`, which:
- allows the component to take advantage of inherent color transitions
- importantly retains the link within the tab index for improved accessibility
- improve CSS spacing to mimic [`Span.StartIcon`](https://zendeskgarden.github.io/react-components/typography/#span) styling and increase desktop tap target
@allisonacs you'll be pleased to know that this nabs …
=> fix: autolink header styling

src/components/MarkdownProvider/components/OverviewLinks.tsx
**Jira - GARDEN-1370**
This PR aims to better handle the semantic tags on the overview pages.
=> chore: update overview tags

src/layouts/Home/components/News.tsx, src/layouts/Home/components/Search.tsx, src/layouts/Root/components/Header.tsx
**Fix Jira [GARDEN-1404]**
Revises the news section alignment to vertically fall in line with section above it.
=> chore: update home alignment

src/layouts/Titled/components/TOC.tsx
Closes Jira [GARDEN-1453]
This PR refines the overflow behavior of the Table of Contents so we don't have a persistent scroll bar shell in places where it isn't necessary.
=> fix: refine table of contents overflow

src/pages/components/button-group.mdx, src/pages/components/button.mdx, src/pages/components/split-button.mdx
**Fixes Jira [GARDEN-1400]**
This PR aligns the way we refer to button sizes for the pages:
- `Button`
- `Icon Button`
- `Button Group`
- `Split Button`
=> fix: amend button size strings

src/layouts/Root/components/Footer.tsx
This PR fixes a failing contrast ratio for the footer links they are hovered by inheriting the white font color upon hover.
=> fix(footer): improve footer link contrast on hover

src/examples/button/SplitButtonDanger.tsx, src/examples/button/SplitButtonDefault.tsx, src/examples/button/SplitButtonDisabled.tsx, src/examples/button/SplitButtonSizes.tsx, src/examples/button/SplitButtonTypes.tsx, src/pages/components/checkbox.mdx, src/pages/components/icon-button.mdx, src/pages/components/split-button.mdx
**Fixes Jira [GARDEN-1401]**
Adds default, danger and disabled examples to the Split Button component page using other Button page copy syntax as a template for the text.
=> feat: add split button examples

src/components/MarkdownProvider/components/CodeExample/index.tsx
=> fix: prevent code block from overflowing rounded container borders

src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts, src/examples/tooltip/TooltipDefault.tsx, src/examples/tooltip/TooltipPlacement.tsx, src/examples/tooltip/TooltipSize.tsx, src/examples/tooltip/TooltipType.tsx, src/nav/components.yml, src/pages/components/tooltip.mdx
This PR adds the Tooltip component to the website.
=> feat(tooltips): add tooltip component

src/components/MarkdownProvider/components/OverviewLinks.tsx
React keys were missing for the overview links which helps React identify changes in lists.
This PR adds a `key` value for [list fragments](https://reactjs.org/docs/fragments.html#keyed-fragments) and removes empty fragments in favor of `null` (which tells React to render nothing).
**Before:** Warning
**After:** No warning
=> fix: add react keys to overview links

src/layouts/Root/index.tsx
Applying `height: 100%` to the `<html>` element [causes](https://github.com/willmcpo/body-scroll-lock/issues/182#issuecomment-699714361) the browser to scroll to the top when `overflow: hidden` is applied to the `body`. To see this problem, visit `Modal` [documentation](https://garden.zendesk.com/components/modal#size), scroll the page, select "Open Large Modal" and **the browser automatically scrolls the page to the top**. This problem is more apparent with the current `DrawerModal` as outlined here: https://github.com/zendeskgarden/website/pull/188#pullrequestreview-500559432.
It looks like the `height` styles in question were used to make [the footer stick to the bottom](https://dev.to/hzburki/100-height-to-all-divs-gatsby-33nd). However, I think these styles might be unnecessary …
=> fix: remove unnecessary global height styles

src/components/MarkdownProvider/components/CodeExample/index.tsx, src/examples/table/TableCaption.tsx, src/examples/table/TableDefault.tsx, src/examples/table/TableGroupedRows.tsx, src/examples/table/TableOverflow.tsx, src/examples/table/TablePagination.tsx, src/examples/table/TableScroll.tsx, src/examples/table/TableSelectRows.tsx, src/examples/table/TableSize.tsx, src/examples/table/TableSort.tsx, src/examples/table/TableStripedRows.tsx, src/examples/table/TableTruncate.tsx
The `overflow: auto` styling added to the component example wrapper in the latest Table PR brought with it some undesirable behavior on other examples. This PR addresses that problems and handles the overflow behavior for the Tables in the Table example code instead.
=> fix: amend component overflow style

.circleci/config.yml
With us experiencing more frequent build failures in CircleCI, it appears that adjusting the [multi-core settings](https://www.gatsbyjs.com/docs/multi-core-builds/) helps us reliably build.
It looks like CircleCI is hyper-threading with a logical CPU count of `36`. This is causing the terser webpack plugin to run out of memory intermittently. By pinning the `GATSBY_CPU_COUNT` environment variable to match the physical cores (2) of the container this should help us going forward.
I'm going to run this build a few times to make sure that it is passing consistently.
=> fix(build): pin default Gatsby CPU count

src/components/MarkdownProvider/components/CodeExample/index.tsx
This PR proposes to allow overflow for code examples which would allow `SplitButton` to overflow rather than to be clipped.
It looks like originally `overflow: hidden;` was applied to `CodeExample` to prevent code block from overflowing rounded container borders. To address both the `SplitButton` and the original rounded border overflow issue, I've removed `overflow: hidden;` and applied rounded borders to the `CodeBlock` component.
**Before:** overflowed menus were clipped
--------
**After:** overflowed menus are no longer clipped
=> fix: allow overflow in code example

src/pages/content/punctuation.mdx
Publishing new standard for empty states and periods in punctuation
=> feat(content): add empty state to period standard

src/pages/content/grammar.mdx
As part of the bug bash, it was noted that the table examples in the "Tense" example of the content section would be better suited in Do this/Not this examples as opposed to a table. This PR proposes that update.
=> fix(content): update tense example

src/pages/design/icons/installation.mdx
As part of the bug bash, it was noted the copy references an example that doesn't exist on the icons page. This removes that reference.
=> fix(icons): remove example reference

.github/PULL_REQUEST_TEMPLATE.md, src/examples/typography/code-block/Default.tsx, src/examples/typography/code-block/Language.tsx, src/examples/typography/code-block/Light.tsx, src/examples/typography/code-block/Numbered.tsx, src/examples/typography/code-block/Size.tsx, src/nav/components.yml, src/pages/components/code-block.mdx
Adds a new `Typography / Code block` component page.
@steue I winged it on the examples and several copy modifications. Please review with a critical eye.
=> feat(typography): add code-block component page

src/examples/forms/input-group/ButtonPlacement.tsx, src/examples/forms/input-group/Disabled.tsx, src/examples/forms/input-group/InputGroup.tsx, src/examples/forms/input-group/Readonly.tsx, src/examples/forms/input-group/Size.tsx, src/nav/components.yml, src/pages/components/input-group.mdx
This PR introduces the documentation for the [InputGroup](https://zendeskgarden.github.io/react-components/forms/#input-group) component.
=> feat: add InputGroup documentation

src/pages/content/punctuation.mdx
This was a request by the localization team. I have added the punctuation symbol to each heading so it's more easily scanned. My initial impulse is to put the symbol in parentheses, but I am open to other design solutions!
=> feat(content): Improve scannability with punctuation symbols in headings

src/examples/dropdowns/menu/Nested.tsx
It looks like the nested menu example has a regression from how it [previously behaved](https://garden-v7.netlify.app/dropdowns/#!/Menu%20usage/7) in the v7 example. The problem is that when a user switches between menus no item is highlighted.
The `onStateChange` callback has some incorrect logic which this PR fixes. When navigating between the parent and nested menus, the menu item at index 1 should be highlighted. Also, `'flowers'` is not an item that exists in the example so that has been removed.
**Before**: The user switches between menus no item is highlighted
--------
**After**: The user switches between menus and the first item (or the previous parent item) is highlighted.
=> fix(dropdowns): fix nested menu to highlight correct item

package.json, src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts, src/examples/forms/file-upload/Disabled.tsx, src/examples/forms/file-upload/FileUpload.tsx, src/examples/forms/file-upload/Size.tsx, src/nav/components.yml, src/pages/components/file-upload.mdx, yarn.lock
This PR adds the documentation for the `FileUpload` component. The DO/DONT layer isn't merged into abstract yet, but that will be added once available.
=> feat: new FileUpload documentation page

package.json, src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts, src/examples/table/TableScroll.tsx, src/examples/table/TableVirtualized.tsx, yarn.lock
Depending on the OS, browser, and system preferences users may see different scrollbar styling for the scroll and virtualized table examples.
This PR adds additional logic to ensure that table headers align with body columns.
Native tables are hard to style sometimes. The same reasons that makes scrollable tables a custom implementation, padding/margin limitations, require us to include a hidden cell rather than styling the `<tr>` directly.
=> fix: ensure scrollable table handle unique scrollbar sizes

src/components/MarkdownProvider/components/Color.tsx, src/components/MarkdownProvider/components/ColorPalette.tsx, src/components/MarkdownProvider/index.tsx, src/nav/design.yml, src/pages/design/color.mdx
Find the new page under the `/design/color` URL.
- the palette component uses Polished [readableColor](https://polished.js.org/docs/#readablecolor) to determine light-on-dark text
- the `ColorPalette` component makes it easy to rearrange hues within a palette on the `website`; rearranging shades within a hue will require adjustments to `react-components` source code (cc @allisonacs, it will be good to get your :eyes: on the current 🌈  ordering)
- I made some guesses about vertical spacing (20px top; 40px bottom) based on other components such as `CodeExample`
=> feat: add Design / Color documentation

package.json, src/components/MarkdownProvider/components/ColorPalette.tsx, src/examples/design/icons/SvgSearch.tsx, yarn.lock
From the following config, we can see that paragraphs and list items are eligible for DocSearch indexing.
https://github.com/algolia/docsearch-configs/blob/master/configs/garden_zendesk.json
This PR restructures the DOM for colors and icons in order to facilitate indexing. We won't know until 24 hours (crawler lag time) after merge whether these changes succeed or not.
=> chore: restructure colors and icons for search indexing

src/components/MarkdownProvider/components/Anchor.ts
Added focus styling to anchor links.
Following similar styling seen on https://www.gatsbyjs.com/plugins/gatsby-image/.
=> fix: anchor link focus styling

gatsby-config.js
- turn `disableBgImageOnAlpha` on – per [gatsby](https://www.gatsbyjs.com/plugins/gatsby-remark-images/#options), images with transparent pixels result in blurry edges
- turn `linkImagesToOriginal` off – we don't want the ability to click-through to full-size images
Fixes the background blur (and anchored image) seen here: https://garden.zendesk.com/content/voice-and-tone#mapping-tone
=> fix: gatsby-remark-images options

plugins/gatsby-source-react-packages/gatsby-node.js, src/components/MarkdownProvider/components/Configuration.tsx, src/pages/components/checkbox.mdx, src/pages/components/code.mdx
- `Code` size copy
- Configuration links should use `isExternal`
- Update `react-components` to match package.json
=> fix: clean up some copy and anchor bugs

src/layouts/Titled/index.tsx
This PR updates the DOM ordering of the table-of-contents. It now renders before the main page content for keyboard and assistive device users.
=> fix(a11y): ensure table of contents renders in correct DOM order

src/nav/components.yml
Prevent zendeskgarden/css-components#326 from nuking the link. The updated location is really where this should've been pointing to all along. The demo page offers little to no actual documentation.
=> chore: replace Bedrock CSS link

src/pages/components/versions.mdx
Use links that are administered by the internal zendesk-garden account.
=> chore(versions): update links to previous versions

src/pages/content/word-list.mdx
Update wordlist copy from "Help Center" to "help center" per content design.
**Before:**
**After:**
=> fix: update help center copy for content design

package.json, yarn.lock
It appears that changes under `gatsby-plugin-styled-components` [v4.14.0](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-styled-components/CHANGELOG.md#4140-2021-09-18) are resulting in the following render errors for component page examples:
```
The `StyleSheetManager` expects a valid target or sheet prop!
```
This PR rolls back to the last known working version v4.11.0. Given the nature of the breakage, I will merge this PR upon successful CI staging deploy.
Fixes #304 
The issue merged uncaught with the following Renovate: https://github.com/zendeskgarden/website/pull/298.
See https://github.com/gatsbyjs/gatsby/pull/33147 for details.
=> fix(deps): rollback `gatsby-plugin-styled-components`

src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts, src/examples/color-swatch/ColorSwatchCustomTrigger.tsx, src/examples/color-swatch/ColorSwatchDefault.tsx, src/examples/color-swatch/ColorSwatchDialog.tsx, src/nav/components.yml, src/pages/components/color-picker.mdx, src/pages/components/color-swatch.mdx
This pull request adds the color swatch documentation page to the website.
=> feat(colorpickers): add color swatch page

src/fragments/dropdowns-filtering-notes.mdx
Added a note to the Dropdown implementation notes, keeping in line with IME issues encountered historically when the `onStateChange` prop was used and resolved by replacing with `onInputValueChange` prop instead to update internal state. All examples in Dropdowns have already been updated to replace `onStateChange` usage with `onInputValueChange`.
designer as a reviewer)~~
=> chore(docs): Add a note about IME support to Dropdowns

src/examples/table/TableOverflow.tsx
A recent PR to document and improve table [overflow](https://github.com/zendeskgarden/website/pull/322) accessibility inadvertently diminished overflow menu behavior. This PR restores the [overflow](https://garden.zendesk.com/components/table#overflow) behavior.
Thanks to @hzhu for a reminder re: React `forwardRef` needed to retain button functionality within a `Tooltip`.
=> fix(tables): extract overflow tooltip into a forwardRef

src/nav/content.yml, src/pages/content/actionable-language.mdx, src/pages/content/word-list.mdx
This PR adds a new content section "Actionable language".
Adding the new section "Actionable language" and removing some of the words from the "Word list" page for clarity.
The actionable language has been put under a new sub nav category "Guides".
=> feat(content): add actionable language page

src/pages/components/date-picker.mdx
Removing `moment.js` as a recommended solution for formatting dates.
Due to `moment.js` currently being a legacy library that is not actively maintained, as well as being not tree shakable, we should not be recommending it in our documentation.
=> chore(components/datepicker): remove momentjs from recommended date formatting libraries

src/examples/chrome/SheetDefault.tsx, src/examples/chrome/SheetFooters.tsx, src/examples/chrome/SheetHeaders.tsx, src/examples/chrome/SheetPlacement.tsx, src/examples/chrome/SheetSize.tsx, src/nav/components.yml, src/pages/components/sheet.mdx
This PR adds documentation for the `Sheet` component.
The PR adds the `Sheet` component with 5 examples and documentation for usage and API.
=> feat(sheet): add documentation

src/layouts/Home/components/Search.tsx
Use Garden typography component for home page heading to leverage as much Garden components as possible. There should be no visual difference.
=> fix: use garden component for heading

src/pages/design/icons/12.mdx
This PR adds a hard-coded example to see if Docsearch picks up a hidden element that matches a selector defined in the configuration.
Prerequisite to #352 - there will be future plans to remove this change.
=> chore(algolia): test hidden element is parsed by docsearch

src/pages/components/well.mdx
Remove the Close API from the Well component documentation per
> Although Close could exist in a Well, design intent is that it never would. So it should be removed from this particular page.
=> docs(well): remove close api

src/pages/content/principles.mdx
Update "UX content strategy" and "UX content strategists" to "content design" and "content designers". Team title and role are now up to date.
=> chore(content): update content design team name and title

src/pages/design/icons/index.mdx
Replaces the URL that points to `svg-icons` readme with a cleaner/preferred URL.
=> fix(icons): replace svg-icons repo's readme link to preferred/cleaner url

src/pages/content/word-list.mdx
Add 2 words "default" and "system" to the word list. Saw "stats" was out of alphabetical order and repositioned it.
=> chore(content): add default and system to word list and fix stats to be in alphabetical order

src/examples/design/icons/SvgSearch.tsx, src/nav/design.yml, src/pages/components/chrome.mdx, src/pages/design/icons/chrome-icons.mdx, src/pages/design/icons/library.mdx
Adds the 26px icons back into the website with a description of their usage.
Also, added a new prop for `svgSearch`, in order to control the collapsible. 
This PR also adds a section to the Chome component page that redirects the user to the 26px icons.
The hyperlink will direct the user a library of chrome icons (26px).
=> feat(chrome): Adds back 26px icons onto the website with textual context

src/components/MarkdownProvider/components/BestPractice.tsx
The images within `BestPractice` are considered decorative since they are figures accompanied by a caption. Level access has determined that the alt text is unnecessary because the `figcaption` text is sufficient.
This change affects all usages of `BestPractice`:
1) timeline, autocomplete, avatar, checkbox, combobox, and toggle-icon-button component pages.
2) word-list, actionable language, grammar, and punctuation content pages
3) icons page
4) patterns page
=> fix: apply empty string alt for decorative images

src/pages/design/icons/index.mdx, src/pages/design/icons/library.mdx
Fix some titles within the design page to follow Garden's grammar guidelines.
Before:
---
After:
=> fix(design): convert titles to sentence case

src/examples/table/TableSelectRows.tsx
The checkboxes within the table now have a unique label to discern the specific purpose of each field.
`Before`
Screen reader wasn't able to distinguish each field due to identical labels.
`After`
=> fix(tables):  Provided a valid label for form fields

.github/workflows/deploy.yml
This PR fixes the GH action that was missing keys and caused invalid syntax.
References that were used:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
https://github.com/actions/checkout
=> chore(actions): fix deploy workflow

.github/workflows/deploy.yml
This PR enables the use of [HTTPS instead of SSH when cloning down submodules](https://github.com/actions/checkout). This will allow the cloning of `react-components`.
=> chore(workflows): enable submodules in checkout action

src/examples/accordions/stepper/StepperDefault.tsx
This PR updates one of the `Stepper` component examples to use a `tabIndex` of `-1` when in a selected step.
=> chore(examples/stepper): add tab index to buttons in active step

src/examples/breadcrumbs/BreadcrumbsDefault.tsx, src/examples/tooltip/TooltipDefault.tsx, src/examples/tooltip/TooltipPlacement.tsx, src/examples/tooltip/TooltipSize.tsx, src/examples/tooltip/TooltipType.tsx
This PR adds some improvements to the examples by using more accessible examples.
Changes were made to:
- `Breadcrumb` - added `href` to allow tabbing to occur
- `Tooltip` - replaced `<span />` element with a `<Button />` component to use interactive elements
=> fix(examples): improve with more accessible examples

gatsby-config.js, src/nav/patterns.yml, src/pages/patterns/rich-text-editor.mdx
Added rich-text editor pattern documentation page with image examples.
=> docs: Add rich-text editor pattern docs

src/examples/table/TableDraggable.tsx
This PR adds the subject item for the interactive control (button) that is used for dragging the rows. The experience will allow the drag and drop to announce the controls while announcing the name for each row.
=> fix(components): update table draggable example to be more a11y friendly

src/examples/table/TableDraggable.tsx
Corrects the color for the draggable `Table` component example - uses the 600 and 700 shades of the `primaryHue`.
=> fix(components): correct table draggable icon handle color

package.json, yarn.lock
Reverts #409 which has problems rendering frontmatter. A repeat of #397 🤦.
=> fix(deps): revert dependency gatsby-plugin-mdx to v2.14.0

src/pages/components/table.mdx
In Table component page's API documentation, we include links that connect the SortableCell, GroupRow, and OverflowButton notes to their corresponding page sections. Until now, these links were all labelled as "example." This PR adds the name of the page section to each link label:
- "example" ➡️ "SortableCell example"
- "example" ➡️ "GroupRow example"
- "example" ➡️ "OverflowButton example"
It's important that we communicate the purpose and/or destination of these links to users — especially users who rely on screen readers and other assistive technology — so that they understand exactly where they'll go, if they click on the link. 
https://user-images.githubusercontent.com/93289772/195148037-ec223799-df44-477c-bd90-11ff308f6c26.mov …
=> feat(table): add section names to SortableCell, GroupRow, and OverflowButton example links

src/examples/forms/file-upload/FileList.tsx, src/examples/forms/file-upload/FileUpload.tsx
This PR adds ARIA labels to the File upload examples. These labels provide context for users who rely on screen readers and other assistive tech.
In places where the Progress component is not visible in the UI, `aria-hidden="true"` was applied, in order to hide the component from assistive tech. However, upon further inspection, it seems it may be cleaner to remove the Progress component from `FileList.tsx` on lines 34 and 98. What do you think, @zendeskgarden/maintainers? 
https://user-images.githubusercontent.com/93289772/196238996-0c90a5bf-5337-492b-8b05-ab604fade72c.mov
https://user-images.githubusercontent.com/93289772/196242409-a4cada98-38c1-4ceb-b27a-f6998bf05ff5.mov
=> feat(file-upload): add ARIA labels to component examples

src/pages/components/avatar.mdx, src/pages/components/button.mdx, src/pages/components/file-upload.mdx, src/pages/components/icon-button.mdx, src/pages/components/radio.mdx, src/pages/components/stepper.mdx, src/pages/components/toggle-icon-button.mdx
On several component pages, we include links that navigate the user to sections within those pages. Until now, these links were all labelled as "example." This PR adds the name of the page section to each link label.
It's important that we communicate the purpose and/or destination of these links to users — especially users who rely on screen readers and other assistive technology — so that they understand exactly where they'll go, if they click on the link.
=> feat: add section names to example links across multiple component pages

src/examples/drawer/DrawerDefault.tsx, src/examples/modal/ModalDanger.tsx, src/examples/modal/ModalDefault.tsx, src/examples/modal/ModalSize.tsx, src/examples/tooltip-modal/TooltipModalDefault.tsx, src/examples/tooltip-modal/TooltipModalPlacement.tsx
In order to render the Modal, Tooltip Modal, and Drawer titles as headings, this PR passes values to their title components' tag props. Headings help assistive tech users orient themselves and navigate around a web page.
=> feat(modals): add h2 elements to Modal, Tooltip Modal, and Drawer component examples

src/examples/forms/tiles/TilesDefault.tsx, src/examples/forms/tiles/TilesDescription.tsx, src/examples/forms/tiles/TilesDisabled.tsx, src/examples/forms/tiles/TilesLayout.tsx
The ARIA label for each Tiles component example now includes that example's section name. This ensures each label is unique, which will make navigation and wayfinding easier for folks who rely on assistive tech.
=> feat(tiles): add section name to each example's ARIA label

src/layouts/Root/components/Header.tsx
Shows `/patterns` link on mobile navigation menu.
Since we've added patterns, the mobile link has been commented out - this PR uncomments to show patterns on mobile navigation menu.
=> fix: show patterns link on mobile

src/examples/notifications/alerts/AlertType.tsx, src/examples/notifications/notifications/NotificationType.tsx
This PR adds the name of each Alert or Notification and type to all of the close button labels in the Types section. This ensures each close button's text label is unique, which helps AT users navigate the page more easily.
e.g., 
* Before: `Close Alert`
* After: `Close Info Alert`
e.g.,
* Before: `Close Notification`
* After: `Close Info Notification`
=> feat(notifications): add type name to each Type demo's close button label, for both Alerts & Notifications

src/examples/forms/checkbox/Default.tsx
Wraps the default `Checkbox` component example with `Fieldset` and `Fieldset.Legend` component.
=> fix(examples): update default checkbox example with fieldset component

src/pages/components/theme-object.mdx
URL was pointing to a non-existent page. Fixes to point to the `#installation` anchor on  `design/icons` page.
=> fix(components): fix icons installation url

src/components/MarkdownProvider/components/PropSheet.tsx
Values in Default column cells can contain Tags, and DIVs shouldn't be inside SPANs.
Before:
After:
=> fix(examples): in prop sheet, use 'div' to wrap cell content in Default column

src/examples/table/TableDraggable.tsx
✅ `v8.63.1` on `main`, branch rebased
Applies new `hidden` prop to empty cell header on Tables' draggable row example.
=> fix(examples): adds hidden prop to empty cell on draggable table rows example

src/pages/patterns/drag-and-drop.mdx
Adds link to drag and drop pattern for dnd docs.
=> fix: re-adds pattern link to dnd pattern docs

src/components/MarkdownProvider/components/Alert.tsx, src/components/MarkdownProvider/components/OverviewLinks.tsx, src/components/MarkdownProvider/index.tsx, src/layouts/Root/components/StyledNavigationLink.tsx, src/layouts/Sidebar/components/DesktopSidebar.tsx, src/layouts/Sidebar/components/MobileSidebar.tsx, src/layouts/Sidebar/components/NavItemTitle.tsx, src/nav/components.yml, src/pages/components/button-group.mdx
This PR is a prerequisite for the new `Combobox` page as I want the ability to tag deprecated dropdowns and alert folks to the new, replacement component. The basic gist is that `(tag)` type notation can be added to [components.yml](https://github.com/zendeskgarden/website/blob/main/src/nav/components.yml) in order to render Garden tags in the navigation UI. The words "deprecated" and "new" get special hue treatment (see below). Otherwise, the standard neutral tag color is applied.
In addition, a new `Alert` markdown component was added in order to render Garden alerts at the top of a (deprecated) component page.
Here are a few tag examples (only Button group is committed with this PR):
And here's the before/after on the Button group page showing use of the `<Alert>`:
**before**
**after**
=> feat: add nav tags and page alerts

.github/PULL_REQUEST_TEMPLATE.md, src/examples/chrome/GlobalAlert.tsx, src/pages/components/chrome.mdx
Adds new "Global alert" example to the Chrome component page.
=> chore(chrome): add GlobalAlert example

gatsby-config.js
The latest SVGO requires updated syntax.
Broke with #500
=> fix: restore SVG `viewBox` attributes

src/examples/design/icons/SvgSearch.tsx
Eradicates the non-essential design and non-accessible [disclosure](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) pattern introduced by #348.
=> chore(icons): remove "view all icons" button

src/pages/components/chrome.mdx
Updated copy with noted a11y clarification.
=> chore(chrome): clarify nav `hue` copy

src/components/MarkdownProvider/components/CodeExample/utils/retrieveCodesandboxParameters.ts
Adds missing `react-forms` to codesandbox parameters.
=> fix: adds react-forms to sandbox dependencies

plugins/gatsby-source-garden-docgen/README.md, src/components/MarkdownProvider/components/Configuration.tsx, src/pages/index.tsx
Fix external URLs to NPM and Github
- Fix external URLs to NPM and Github
- Improves type safety
- Remove redundant packageName aliased field from query
=> fix: correct external URLs to NPM and Github

.eslintrc.js, package-lock.json
Following the [ESLint v9 update](https://github.com/zendeskgarden/website/pull/585), running `gatsby develop` via `npm start` prevented development and threw the following error:
```
ERROR #98123  WEBPACK.DEVELOP
Generating development JavaScript bundle failed
Invalid Options:
- Unknown options: extensions, useEslintrc, resolvePluginsRelativeTo, rulePaths
- 'extensions' has been removed.
- 'resolvePluginsRelativeTo' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
failed Building development bundle - 39.711s
ERROR in Invalid Options:
- Unknown options: extensions, useEslintrc, resolvePluginsRelativeTo, rulePaths
- 'extensions' has been removed.
- 'resolvePluginsRelativeTo' has been removed.
- 'rulePaths' has been removed. Please define your rules …
```
=> chore: add empty project .eslintrc to disable Gatsby's eslint loaders 

package-lock.json, package.json, src/components/MarkdownProvider/components/BestPractice.tsx, src/components/MarkdownProvider/components/CodeExample/index.tsx, src/components/MarkdownProvider/components/ColorPalette.tsx, src/components/Provider.tsx, src/examples/draggable/DropzoneDefault.tsx, src/examples/table/TableVerticalScrolling.tsx, src/examples/theme-provider/ThemeProviderBranding.tsx, src/examples/theme-provider/ThemeProviderExtension.tsx, src/examples/theme-provider/ThemeProviderNesting.tsx, src/examples/theme-provider/ThemeProviderTargeting.tsx, src/layouts/Home/components/News.tsx, src/layouts/Root/components/Footer.tsx, src/layouts/Root/components/Header.tsx, src/layouts/Root/components/StyledNavigationLink.tsx, src/layouts/Sidebar/index.tsx
Upgrades to `@zendeskgarden/react-theming@next` and limit refactoring to `src/components` and `src/layout`.
- upgrade to `@zendeskgarden/react-theming@next`
- replace missing colors from V8 `theme.colors` with `getColor({ variable: {{variable}}, theme)`
- Refactor obvious colors assignments with `getColor`
- Remove deprecated `focusVisibleRef`
- Fix TS error everywhere, including `src/examples`, to successfully pass tests and build
=> refactor: upgrade to `@zendeskgarden/react-theming@next`

src/layouts/Titled/components/TOC.tsx, src/pages/components/autocomplete.mdx, src/pages/components/chrome.mdx, src/pages/components/color-picker.mdx, src/pages/components/combobox.mdx, src/pages/components/date-picker.mdx, src/pages/components/draggable.mdx, src/pages/components/drawer.mdx, src/pages/components/legacy-combobox.mdx, src/pages/components/legacy-menu.mdx, src/pages/components/legacy-select.mdx, src/pages/components/menu.mdx, src/pages/components/multiselect.mdx, src/pages/components/pagination.mdx
This is a prep PR to ensure component pages hold together. Once this merges, those pages can be updated in parallel. **These changes are minimal** to keep the diff small.
As usual, some colors/details will be off, which is intended while the migration process continues.
The [migration guide](https://github.com/zendeskgarden/react-components/blob/next/docs/migration.md) was used for details on specific naming/path updates.
Each component page was loaded to validate, including sub-pages (`forms > multiselect`, for instance).
=> chore: updates components submodule to v9

package-lock.json, package.json, src/examples/accordions/accordion/AccordionBare.tsx, src/examples/accordions/accordion/AccordionDefault.tsx, src/examples/accordions/accordion/AccordionExpandable.tsx, src/examples/accordions/accordion/AccordionSize.tsx, src/examples/accordions/stepper/StepperIcons.tsx, src/examples/accordions/stepper/StepperLayout.tsx, src/examples/accordions/timeline/TimelineCustomMedia.tsx, src/examples/accordions/timeline/TimelineDefault.tsx
Updates accordions (including timeline and stepper) to v9 & applies relevant v9 changes to package examples.
Follows [migration guide](https://github.com/zendeskgarden/react-components/blob/next/docs/migration.md) where applicable.
=> feat(components): update accordions to v9

package-lock.json, package.json, src/examples/breadcrumbs/BreadcrumbsDefault.tsx
Upgrade `breadcrumbs` component page to v9 following the [migration guide](https://github.com/zendeskgarden/react-components/blob/next/docs/migration.md) changes.
=> feat(components): update `breadcrumbs` to v9 

package-lock.json, package.json, src/examples/loaders/dots/DotsColor.tsx, src/examples/loaders/dots/DotsDefault.tsx, src/examples/loaders/dots/DotsSize.tsx, src/examples/loaders/inline/InlineColor.tsx, src/examples/loaders/inline/InlineDefault.tsx, src/examples/loaders/inline/InlineSize.tsx, src/examples/loaders/progress/ProgressColor.tsx, src/examples/loaders/progress/ProgressDefault.tsx, src/examples/loaders/progress/ProgressSize.tsx, src/examples/loaders/skeleton/SkeletonDefault.tsx, src/examples/loaders/skeleton/SkeletonLight.tsx, src/examples/loaders/skeleton/SkeletonSize.tsx, src/examples/loaders/spinner/SpinnerColor.tsx, src/examples/loaders/spinner/SpinnerDefault.tsx, src/examples/loaders/spinner/SpinnerSize.tsx
Upgrade `loaders` component pages to v9 following the [migration guide](https://github.com/zendeskgarden/react-components/blob/next/docs/migration.md) changes.
=> feat(components): update `loaders` to v9 

package-lock.json, package.json, src/examples/draggable/DraggableBare.tsx, src/examples/draggable/DraggableContent.tsx, src/examples/draggable/DraggableDefault.tsx, src/examples/draggable/DraggableDisabled.tsx, src/examples/draggable/DraggableListDefault.tsx, src/examples/draggable/DraggableListHorizontal.tsx, src/examples/draggable/DraggableListIndicator.tsx, src/examples/draggable/DraggablePlaceholder.tsx, src/examples/draggable/DraggableSize.tsx, src/examples/draggable/DropzoneDanger.tsx, src/examples/draggable/DropzoneDefault.tsx
**Package migration changes:**
- Updates `react-drag-drop` to `react-draggable` (v9)
**Other updates:**
- Updates examples 
- Use `Grid` subcomponent properties
- Apply custom colors to support dark mode (headings in `DraggableList` and `Dropzone` examples)
https://github.com/user-attachments/assets/83d92bf8-cc34-4559-a7f2-09450f9df511
Notes:
- No changes to MDX file(s)
=> feat(components): update draggable to v9

.lintstagedrc
Temporarily removes ESLint --max-warning flag from lint-staged config (omission from refactor(component pages): reference updated subComponents' displayName #621).
=> chore: removes ESLint `--max-warning` flag from lint-staged config

package-lock.json, package.json, src/components/MarkdownProvider/components/CodeExample/index.tsx, src/examples/tabs/TabsDefault.tsx, src/examples/tabs/TabsDisabled.tsx, src/examples/tabs/TabsVertical.tsx, src/examples/theme-provider/ThemeProviderTargeting.tsx
Updates `react-tabs` to v9.
- Refactors examples to use `Tabs`' subComponent properties
- Set `CodeExample`’s text color to `foreground.default` var
=> feat(components): update `tabs` to v9

src/examples/grid/GridAllBreak.tsx, src/examples/grid/GridColumnBreaks.tsx, src/examples/grid/GridColumnWrapping.tsx, src/examples/grid/GridEqual.tsx, src/examples/grid/GridEqualMulti.tsx, src/examples/grid/GridHorizontal.tsx, src/examples/grid/GridNesting.tsx, src/examples/grid/GridNoGutters.tsx, src/examples/grid/GridOffset.tsx, src/examples/grid/GridOneCol.tsx, src/examples/grid/GridReordering.tsx, src/examples/grid/GridStacked.tsx, src/examples/grid/GridVariable.tsx, src/examples/grid/GridVertical.tsx, src/examples/pane/PaneGrid.tsx, src/examples/pane/PaneHorizontal.tsx, src/examples/pane/PaneHorizontalCollapse.tsx, src/examples/pane/PaneVertical.tsx, src/examples/pane/PaneVerticalCollapse.tsx, src/examples/pane/SplitterButtonPosition.tsx
Updates Pane and Grid pages to support v9 changes.
**Migration guide changes:**
**Demo-specific changes:**
**Completed in previous PRs:**
- Updates to MDX files
**Grid**
https://github.com/user-attachments/assets/cab8805f-3a2e-4728-8e06-a070b32e0eb9
**Pane**
https://github.com/user-attachments/assets/f0251620-2d8f-463a-8bf4-576396f4d963
=> feat(components): updates grid to v9

src/examples/draggable/DraggableListDefault.tsx, src/examples/draggable/DraggableListHorizontal.tsx, src/examples/draggable/DraggableListIndicator.tsx, src/examples/draggable/DraggablePlaceholder.tsx, src/examples/draggable/DropzoneDanger.tsx, src/examples/draggable/DropzoneDefault.tsx
Removing the extra foreground definitions given the central foreground update in #626
=> fix(draggable): removes extraneous foreground colors in examples

package-lock.json, package.json, src/examples/color-picker/ColorPickerDefault.tsx, src/examples/color-picker/ColorPickerDialogCustomTrigger.tsx, src/examples/color-picker/ColorPickerDialogDefault.tsx, src/examples/color-picker/ColorPickerDialogFormInput.tsx, src/examples/color-picker/ColorPickerOpaque.tsx, src/examples/color-swatch/ColorSwatchCustomTrigger.tsx, src/examples/color-swatch/ColorSwatchDefault.tsx, src/examples/color-swatch/ColorSwatchDialog.tsx
Updates `react-colorpickers` to v9.
=> feat(components): update `colorpickers` to v9

package-lock.json, package.json, src/examples/accordions/timeline/TimelineAlternating.tsx, src/examples/accordions/timeline/TimelineCustomMedia.tsx, src/examples/accordions/timeline/TimelineDefault.tsx, src/examples/accordions/timeline/TimelineOppositeContent.tsx, src/examples/draggable/DraggableContent.tsx, src/examples/tooltip-modal/TooltipModalPlacement.tsx, src/examples/typography/code-block/Numbered.tsx, src/examples/typography/code/Color.tsx, src/examples/typography/code/Default.tsx, src/examples/typography/code/Size.tsx, src/examples/typography/lists/Default.tsx, src/examples/typography/lists/Nesting.tsx, src/examples/typography/paragraph/Size.tsx, src/examples/typography/span/Hue.tsx, src/pages/components/span.mdx
Updates `react-typography` to `v9`.
Update pages using typography components with colors:
- ~~ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)~~
=> feat(components): update typography to v9

package-lock.json, package.json, src/layouts/Root/components/StyledNavigationLink.tsx, src/pages/components/theme-object.mdx, src/pages/patterns/buttons.mdx, src/pages/patterns/copy.mdx, src/pages/patterns/drag-and-drop.mdx, src/pages/patterns/errors.mdx, src/pages/patterns/filters.mdx, src/pages/patterns/loaders.mdx, src/pages/patterns/rich-text-editor.mdx, src/pages/patterns/save.mdx, src/pages/patterns/tables/basic-formatting.mdx
- upgrades `@zendeskgarden/css-bedrock` to v10
- removes `background.primary` color variable doc from "Theme object" component page
- removes broken feedback form links from pattern pages
=> fix: `css-bedrock` upgrade, color variable API docs, remove feedback links

src/layouts/Root/index.tsx
The support thread with Algolia uncovered the fact that the website is rendering blank with JavaScript disabled. This PR removes a `typeof window === 'undefined'` check at the root to allow pages to render content. The impact is a slight, occasional page shift due to the v9 global alert. But we need to get a handle on this issue before the more significant dark mode PR lands. This PR is key for that effort.
=> fix(docsearch): enable SSR page rendering

content/figma/assets.yml, content/nav/design.yml, src/components/MarkdownProvider/components/ColorShades.tsx, src/components/MarkdownProvider/index.tsx, src/examples/design/color/BackgroundVariables.tsx, src/examples/design/color/BorderVariables.tsx, src/examples/design/color/ForegroundVariables.tsx, src/examples/design/color/Purpose.tsx, src/examples/design/color/ShadowVariables.tsx, src/layouts/Root/index.tsx, src/pages/design/color.mdx, src/pages/design/palette.mdx
This PR introduces an initial version of the **Color Principles** page. This page has been generated using the Markdown export feature from Google Docs. Future enhancements and refinements, including custom table designs, will be addressed in subsequent PRs.
- The existing **Color** page has been renamed to **Palette** and relocated to `design/palette`.
- A new **Color Principles** page has been added at `design/color`.
=> feat: add Color Principles page

src/pages/components/versions.mdx
This update restores missing links to documentation websites for legacy versions of Garden.
- ~~[ ] :ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)~~
- ~~[ ] :black_nib: copy updates are approved (add the content strategist as a reviewer)~~
- ~~[ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
- ~~[ ] :memo: tested in Chrome, Firefox, Safari, Edge~~
=> fix(versions): links for legacy docs
