zendeskgarden/website

utils/netlify-deploy.ts
The netlify deploy process isn't calculating `draft` deployment statuses correctly.
This PR corrects that logic.
=> Fix netlify deployment environments

src/layouts/Root/components/Header.tsx, src/layouts/Root/components/StyledNavigationLink.tsx, src/layouts/Sidebar/components/DesktopSidebar.tsx, src/layouts/Sidebar/components/MobileSidebar.tsx, src/layouts/Sidebar/index.tsx, src/layouts/Titled/components/TOC.tsx
This PR includes:
- Updates mobile styling for the global Header and Sidebar layouts
- Consolidates styling and states for all Header and Sidebar navigation elements
- Updates Header shadow to use larger box-shadow
- Increases touch-target of sidebar TOC
- Small bug fix to help with valid TOC headings while scrolling
Will be based off of `master` once #20 is merged
=> fix: update navigation states and mobile menus

src/components/MarkdownProvider/index.tsx, src/examples/anchor/AnchorDanger.tsx, src/examples/anchor/AnchorDefault.tsx, src/examples/anchor/AnchorExternal.tsx, src/nav/components.yml, src/pages/components/anchor.mdx, src/pages/components/avatar.mdx
This pull request introduces the Anchor Component Page. Use the `View deployment` button further down this page to view a build of this Pull Request.
=> feat: add anchor component page

package.json, src/examples/dropdowns/SelectDefault.tsx, src/examples/dropdowns/SelectDisabled.tsx, src/examples/dropdowns/SelectHint.tsx, src/examples/dropdowns/SelectSize.tsx, src/examples/dropdowns/SelectValidation.tsx, src/nav/components.yml, src/pages/components/select.mdx, yarn.lock
This PR introduces the Select component page.
=> feat: add select component page

plugins/gatsby-source-abstract/gatsby-node.js
Currently, the build does not fetch all Abstract assets due to an Abstract pagination limit (50 items). As a result, the `components-tabs-horizontal-do` (along with many others assets) is not retrieved. 
This PR updates the code to iterate over all the pages available to fetch all the assets from the Abstract file.
Here's a query for an asset that isn't currently fetched:
```graphql
{
abstractAsset(layerName: {eq: "components-tabs-horizontal-dont"}) {
fileFormat
formatName
layerName
children {
... on File {
name
publicURL
}
}
}
}
```
❌ **Before**: The above GraphQL query fails to retrieve the asset.
✅ **After**: The above GraphQL query successfully retrieves the asset.
=> fix: fetch all abstract assets

src/pages/components/select.mdx
This pull request adds the Configuration section to the Select component page.
=> chore: add config section to select page

src/pages/components/select.mdx
This PR aims to add the relevant prop sheets to the Select component page. In order to use the component, and replicate the example on the page, these dependencies are necessary to outline on the Select page.
=> chore: update select prop sheets

src/pages/components/multiselect.mdx
This PR adds the necessary prop sheets needed for reference in relation to the examples on the Multiselect page.
=> chore: update multiselect api sheets

.eslintrc.json, src/examples/dropdowns/MenuArrow.tsx, src/examples/dropdowns/MenuButton.tsx, src/examples/dropdowns/MenuDisable.tsx, src/examples/dropdowns/MenuDisabled.tsx, src/examples/dropdowns/MenuMedia.tsx, src/examples/dropdowns/MenuMeta.tsx, src/examples/dropdowns/MenuNested.tsx, src/examples/dropdowns/MenuPlacement.tsx, src/examples/dropdowns/MenuSelect.tsx, src/examples/dropdowns/MenuSize.tsx, src/examples/dropdowns/SelectDisabled.tsx, src/examples/dropdowns/SelectValidation.tsx, src/pages/components/menu.mdx
This PR introduces the Menu component page
=> feat: add menu component page 

src/components/MarkdownProvider/components/Configuration.tsx, src/components/MarkdownProvider/components/PropSheets.tsx
...with design specs.
A `react-components` follow-up is needed to restore proper L/R padding to Garden table cells.
=> chore: align API section styling

src/components/MarkdownProvider/components/Usage.tsx, src/pages/components/avatar.mdx
This PR introduces string revisions from UXCS to the Avatar component page. 
We've updated the content for this component page. This is meant to be a prototype for other component pages that follow. You can see some of the rationale for the direction being presented in the Avatar Google doc.
=> chore: update avatar component page

src/components/MarkdownProvider/components/CodeExample/index.tsx, src/layouts/Root/components/Footer.tsx
- Add RTL to code example wrapper
- Update default GitHub link for nav-to-org
=> fix(examples): restore RTL layout

gatsby-config.js, package.json, src/layouts/Root/components/StyledNavigationLink.tsx, yarn.lock
GA global site tag plus outbound link tracking.
Fix `activeClassName` console error on `Link` component.
=> chore: add Google analytics

src/pages/components/anchor.mdx
This PR introduces revised copy from UXCS for the Anchor component page.
=> chore: update anchor copy

src/components/MarkdownProvider/components/BestPractice.tsx, src/examples/button/IconButtonDanger.tsx, src/examples/button/IconButtonDisabled.tsx, src/examples/button/IconButtonShapes.tsx, src/examples/button/IconButtonSizes.tsx, src/examples/button/IconButtonTypes.tsx, src/pages/components/icon-button.mdx
This PR introduces the `IconButton` component page
=> feat: add icon button component

src/components/MarkdownProvider/index.tsx, src/examples/button/SplitButtonSizes.tsx, src/examples/button/SplitButtonTypes.tsx, src/pages/components/split-button.mdx
This PR introduces the `<SplitButton>` component page.
=> feat: add split button component

.markdownlintrc, src/examples/forms/checkbox/Default.tsx, src/examples/forms/checkbox/Disabled.tsx, src/examples/forms/checkbox/Hidden.tsx, src/examples/forms/checkbox/Hint.tsx, src/examples/forms/checkbox/Indeterminate.tsx, src/examples/forms/checkbox/RegularWeightLabel.tsx, src/examples/forms/checkbox/Validation.tsx, src/pages/components/checkbox.mdx
This pull request adds the Checkbox component page.
=> feat: add checkbox component page

src/examples/forms/toggle/Default.tsx, src/examples/forms/toggle/Disabled.tsx, src/examples/forms/toggle/Hidden.tsx, src/examples/forms/toggle/Hint.tsx, src/examples/forms/toggle/RegularWeightLabel.tsx, src/examples/forms/toggle/Validation.tsx, src/pages/components/toggle.mdx
This PR introduces the Toggle component page
=> feat: add toggle component page

src/nav/components.yml, src/pages/404.tsx
...also add "Bedrock CSS" to the components foundation nav.
~@allisonacs leaving this in draft while we sort out how to source the new image.~
=> chore: update 404 page

src/pages/components/multiselect.mdx
The PR introduces updates copy from UXCS for the `Dropdown -> Multiselect` component page.
=> chore: update multiselect component copy

src/pages/components/select.mdx
This PR introduces updated copy from UXCS from the `Dropdowns/Select` component page.
=> chore: update select component copy

src/pages/components/menu.mdx
This PR introduces updated copy from UXCS to the Menu component page.
=> chore: update menu component copy

src/nav/components.yml, src/pages/components/input.mdx
This PR introduces updated content from UXCS and revised ordering of examples on the Input component in Forms.
=> chore: revise input content and order

src/examples/button/ButtonDisabled.tsx, src/examples/button/ButtonMedia.tsx, src/pages/components/button.mdx
The PR revises the content on the <Button> component page to UXCS approved copy.
=> chore: revise button content

src/pages/components/tabs.mdx
This PR introduces updates copy from UXCS for the `Tabs` component page.
=> chore: update tabs component copy

src/examples/forms/checkbox/Default.tsx, src/examples/forms/checkbox/Disabled.tsx, src/examples/forms/checkbox/Hidden.tsx, src/examples/forms/checkbox/Hint.tsx, src/examples/forms/checkbox/Indeterminate.tsx, src/examples/forms/checkbox/RegularWeightLabel.tsx, src/examples/forms/checkbox/Validation.tsx
This pull request updates the example content/copy for the `Checkbox` component page.
The content/copy changes are content approved. Thanks to @vsri1137  for the commits. I am putting this PR up on his behalf. Note a follow-up PR for radio example content will be necessary.
=> chore: update checkbox example content

src/pages/content/word-list.mdx
This PR introduces the Word List page to the UXCS section.
=> feat: add word list page

src/examples/anchor/AnchorDanger.tsx, src/examples/anchor/AnchorDefault.tsx, src/examples/anchor/AnchorExternal.tsx, src/examples/breadcrumbs/BreadcrumbsDefault.tsx, src/examples/button/ButtonStretched.tsx, src/examples/dropdowns/menu/Arrow.tsx, src/examples/dropdowns/menu/Default.tsx, src/examples/dropdowns/menu/Disabled.tsx, src/examples/dropdowns/menu/Meta.tsx, src/examples/dropdowns/menu/Nested.tsx, src/examples/dropdowns/menu/Placement.tsx, src/examples/dropdowns/menu/Size.tsx, src/examples/dropdowns/select/Default.tsx, src/examples/forms/inputs/Bare.tsx, src/examples/forms/inputs/FauxInput.tsx, src/examples/forms/inputs/FocusInset.tsx, src/examples/forms/inputs/Hint.tsx, src/examples/forms/inputs/MediaInput.tsx, src/examples/forms/inputs/Size.tsx, src/examples/forms/inputs/Textarea.tsx
This pull request updates the example content/copy for the Input, Select, Menu, Button, Breadcrumbs, and Anchor component pages.
The content/copy changes are content approved. Thanks to @vsri1137 for the commits. I am putting this PR up on his behalf.
=> chore: various example content updates

src/nav/components.yml
This PR updates the Range component page to navigate to the current documentation for Range.
=> chore: update range page to current url

src/pages/components/button.mdx, src/pages/components/menu.mdx
Addresses and fixes copy brought up in [this comment](https://github.com/zendeskgarden/website/pull/102#pullrequestreview-443484007).
* Update copy for "Default" button.
* Fix duplicate copy under "Menu item"
=> chore: update and fix copy

src/examples/typography/Code.tsx, src/examples/typography/Ellipsis.tsx, src/examples/typography/Lists.tsx, src/examples/typography/Modifiers.tsx, src/examples/typography/Paragraph.tsx, src/examples/typography/Span.tsx, src/examples/typography/TypeScale.tsx, src/pages/components/typography.mdx
This pull request adds the Typography component page.
=> feat: add typography component page

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md, src/components/MarkdownProvider/components/Configuration.tsx, utils/deploy.js
This PR updates the default branch for the repository to `main`. Once merged #110 will need to be rebased onto `main`.
=> chore: move default branch to main

static/_redirects
301 redirect `zendeskgarden.netlify.app` -> `garden.zendesk.com`
- https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects
- https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/#redirects
=> chore: add domain-level redirects

static/_redirects
=> chore: add www domain alias redirect

gatsby-config.js, package.json, yarn.lock
Use `gatsby-plugin-sitemap` to generate a sitemap.xml at the root of the website.
=> feat: add sitemap

static/_redirects
=> chore: add css-components redirect

src/pages/components/toggle.mdx
**Fixes Jira [GARDEN-1391]**
Took a look at the Toggle doc. We didn't outline any graphics for the point being made here and since we don't really advocate for the use of Toggles, thinking we ditch it for now until we can revisit with a more rounded takeaway.
=> chore: omit toggle best practice

src/examples/dropdowns/multiselect/Overflow.tsx, src/examples/dropdowns/multiselect/Size.tsx
Fix the 2 instances of ellipsis in loading strings to match UXCS standards. Both instances were on the `Multiselect` component page.
=> chore: fix loading strings

src/pages/content/voice-and-tone.mdx
**Fix Jira[GARDEN-1378]**
Positions the graphic below the title of the section on the UXCS Voice & Tone page.
=> chore: change img position on uxcs page

gatsby-config.js, src/layouts/Root/components/Footer.tsx
**Fix Jira [GARDEN 1393]**
"beautifully simple" is considered out-moded Brand phrasing. This PR updates all the relevant strings to represent the new Garden byline on the homepage: `The source of truth for tools, standards, and best practices when building products at Zendesk.`
=> chore: update meta strings

src/examples/forms/range/RangeDefault.tsx, src/examples/forms/range/RangeDisabled.tsx, src/examples/forms/range/RangeHint.tsx, src/examples/forms/range/RangeValidation.tsx, src/nav/components.yml, src/pages/components/range.mdx
This PR introduces the Range component page to the website.
=> feat: add range component

package.json, src/examples/loaders/dots/DotsColor.tsx, src/examples/loaders/dots/DotsDefault.tsx, src/examples/loaders/dots/DotsSize.tsx, src/nav/components.yml, src/pages/components/dots.mdx, yarn.lock
This PR introduces the Dots loader component page to the website.
=> feat(loaders): add dots component

package.json, src/examples/loaders/progress/ProgressColor.tsx, src/examples/loaders/progress/ProgressDefault.tsx, src/examples/loaders/progress/ProgressSize.tsx, src/nav/components.yml, src/pages/components/progress.mdx, yarn.lock
This PR adds the Progress component loader to the website.
=> feat(loaders): add progress component

src/examples/loaders/spinner/SpinnerColor.tsx, src/examples/loaders/spinner/SpinnerDefault.tsx, src/examples/loaders/spinner/SpinnerSize.tsx, src/nav/components.yml, src/pages/components/spinner.mdx
This PR adds the Spinner component to the website.
=> feat(loaders): add spinner component

src/examples/loaders/skeleton/SkeletonDefault.tsx, src/examples/loaders/skeleton/SkeletonLight.tsx, src/examples/loaders/skeleton/SkeletonSize.tsx, src/nav/components.yml, src/pages/components/skeleton.mdx
This PR adds the Skeleton loader component page to the website.
=> feat(loaders): add skeleton component

src/examples/forms/tiles/TilesDefault.tsx, src/examples/forms/tiles/TilesDescription.tsx, src/examples/forms/tiles/TilesDisabled.tsx, src/examples/forms/tiles/TilesLayout.tsx, src/nav/components.yml, src/pages/components/tiles.mdx
This PR adds the Tiles component to the website.
=> feat(forms): add tiles component

src/examples/grid/GridAllBreak.tsx, src/examples/grid/GridColumnBreaks.tsx, src/examples/grid/GridColumnWrapping.tsx, src/examples/grid/GridEqual.tsx, src/examples/grid/GridEqualMulti.tsx, src/examples/grid/GridHorizontal.tsx, src/examples/grid/GridNesting.tsx, src/examples/grid/GridNoGutters.tsx, src/examples/grid/GridOffset.tsx, src/examples/grid/GridOneCol.tsx, src/examples/grid/GridReordering.tsx, src/examples/grid/GridStacked.tsx, src/examples/grid/GridVariable.tsx, src/examples/grid/GridVertical.tsx, src/nav/components.yml, src/pages/components/grid.mdx
This PR introduces the Grid component to the website.
=> feat(grid): add grid component

package.json, src/examples/chrome/ChromeDefault.tsx, src/examples/chrome/ChromeNavigation.tsx, src/examples/chrome/ChromeStandaloneHeader.tsx, src/nav/components.yml, src/pages/components/chrome.mdx, yarn.lock
This PR adds the Chrome component documentation and examples to the website.
=> feat(chrome): add chrome component

src/examples/accordions/stepper/StepperDefault.tsx, src/examples/accordions/stepper/StepperIcons.tsx, src/examples/accordions/stepper/StepperLayout.tsx, src/nav/components.yml, src/pages/components/stepper.mdx
This PR adds the Stepper component to the website.
=> feat(accordions): add stepper component

src/pages/components/inline.mdx, src/pages/components/tabs.mdx
Update two instances of links that were unnecessarily going to the old site.
=> chore: update links to new site

package.json, src/examples/modal/ModalDanger.tsx, src/examples/modal/ModalDefault.tsx, src/examples/modal/ModalSize.tsx, src/nav/components.yml, src/pages/components/modal.mdx, yarn.lock
This PR adds the Modal component to the website.
=> feat(modal): add modal component

src/pages/components/tooltip-modal.mdx
See https://garden.zendesk.com/content/grammar#capitalization
=> fix: correct capitalization

src/examples/button/ButtonGroupSize.tsx, src/examples/button/ButtonGroupType.tsx
...using `onSelect` function shorthand.
=> fix(buttons): simplify button-group example code

src/pages/content/punctuation.mdx
Reverts #202 in lieu of a preferred design or copy solution.
=> fix(content): revert punctuation scannability updates

src/layouts/Sidebar/index.tsx
ID requested by DocSearch to help the content scraper.
=> chore: add DocSearch main content ID

src/examples/dropdowns/multiselect/Default.tsx, src/examples/dropdowns/multiselect/Overflow.tsx, src/examples/dropdowns/multiselect/Size.tsx, src/examples/forms/input-group/ButtonPlacement.tsx
Swap `onStateChange` with `onInputValueChange`, which is preferred for IME support.
=> fix(multiselect): use i18n-preferred onInputValueChange

static/google24fd052fab97d4cf.html
Needed to access search property data.
=> chore: add Google Search Console verification

package.json
Remove `@types/react` from `resolutions`. Prefer `npx yarn-deduplicate`.
=> chore: update yarn resolutions

src/pages/components/tags.mdx
=> fix(tags): color example link to theme palette

package.json, tsconfig.json, utils/deploy.js, yarn.lock
Verify available Netlify bandwidth prior to staging deploy.
=> chore(scripts): enhance deploy with added bandwidth checking

gatsby-config.js, src/examples/accordions/components.ts, src/examples/accordions/timeline/TimelineAlternating.tsx, src/examples/accordions/timeline/TimelineCustomMedia.tsx, src/examples/accordions/timeline/TimelineDefault.tsx, src/examples/accordions/timeline/TimelineOppositeContent.tsx, src/nav/components.yml, src/pages/components/timeline.mdx
This PR adds the Timeline component.
=> feat: add Timeline component

src/examples/table/TableOverflow.tsx, src/pages/components/table.mdx
This PR aims to restore and improve component documentation while following our content standards. Consideration was given to:
- providing information in a consistent, simple, clear and accessible way
- avoiding overloading with text or repetition
- using ways to make the content easier to scan quickly
=> chore(api): add descriptions and notes to Table

src/pages/components/select-native.mdx, src/pages/components/select.mdx
This PR aims to restore and improve component documentation while following our content standards. Consideration was given to:
providing information in a consistent, simple, clear and accessible way
avoiding overloading with text or repetition
using ways to make the content easier to scan quickly
=> chore(api): add descriptions and notes to native Select component

src/pages/components/tags.mdx
This PR aims to restore and improve component documentation while following our content standards. Consideration was given to:
- providing information in a consistent, simple, clear and accessible way
- avoiding overloading with text or repetition
- using ways to make the content easier to scan quickly
=> chore(api): add descriptions and notes to Tags

src/examples/button/IconButtonDanger.tsx, src/examples/button/IconButtonDefault.tsx, src/examples/button/IconButtonShapes.tsx, src/examples/button/IconButtonSizes.tsx, src/examples/button/IconButtonTypes.tsx, src/examples/button/ToggleIconButtonDefault.tsx, src/examples/button/ToggleIconButtonIcons.tsx, src/examples/button/ToggleIconButtonShapes.tsx, src/examples/button/ToggleIconButtonSizes.tsx, src/examples/button/ToggleIconButtonTypes.tsx, src/examples/table/TableOverflow.tsx, src/pages/components/anchor.mdx, src/pages/components/button.mdx, src/pages/components/icon-button.mdx, src/pages/components/split-button.mdx, src/pages/components/table.mdx, src/pages/components/toggle-icon-button.mdx
This PR aims to restore and improve component documentation while following our content standards. Consideration was given to:
- providing information in a consistent, simple, clear and accessible way
- avoiding overloading with text or repetition
- using ways to make the content easier to scan quickly
[Notes](https://github.com/zendeskgarden/website/pull/322#issuecomment-983076452)
=> chore(api): add descriptions and notes to components in Buttons package

src/layouts/Root/components/SearchInput.tsx
Update with new index credentials per migration instructions from DocSearch.
Verified that FT search is working as expected and queries are logged in the updated analytics dashboard.
=> chore: update to Algolia DocSearch v3

src/examples/dropdowns/menu/Danger.tsx, src/pages/components/menu.mdx
- Add `isDanger` example to the `menu` component page.
=> feat(dropdown): add "isDanger" example

src/pages/content/actionable-language.mdx
This PR adds some content changes to the "OK" section & Do's and Don'ts.
=> chore(content): actionable language followup

src/pages/components/avatar.mdx
Improve `Avatar` component documentation while following our content standards. 
Consideration was given to:
- providing information in a consistent, simple, clear, and accessible way
- avoiding overloading with text or repetition
- using ways to make the content easier to scan quickly
API Structure
Description for `Avatar.Text`
=> chore(api): add description and notes to Avatar components

src/components/MarkdownProvider/components/Lists.tsx
From pair session with @jzempel to fix list spacing.
=> fix: fix list spacing

src/pages/components/tooltip-modal.mdx
Based on content decisions we decided to rename focus jail to focus loop.
=> docs(tooltip-modal): focus jail to loop

.github/workflows/deploy.yml
This PR corrects the path for deploying the website.
=> chore(actions): correct deploy script path

src/pages/content/actionable-language.mdx
Updated content on "Actionable language" page version 2
=> docs: Updated content on "Actionable language" page

src/examples/chrome/ChromeDefault.tsx, src/examples/chrome/ChromeNavigation.tsx, src/examples/pagination/OffsetDefault.tsx, src/examples/pagination/OffsetGap.tsx, src/examples/pagination/OffsetPadding.tsx, src/examples/table/TablePagination.tsx
This PR improves the `Chrome` navigation with `aria-label` and adds `<nav>` elements around `Pagination` components where used.
=> fix(examples): update to use labeled nav elements and add nav element to Pagination components

gatsby-config.js, src/pages/patterns/tables/basic-formatting.mdx
Fresh off the press! Additions and updates to Tables docs
- Cell formatting
- Row actions
- Wrapping and truncation
- Avators, icons, and tags
Please review for:
- Overall code hygiene
- Copy fixes / nits
- Appropriate cross-reference URLs
=> feat(patterns): Update Tables documentation

src/examples/combobox/Autocomplete.tsx, src/examples/combobox/Multiselect.tsx, src/examples/combobox/Search.tsx
Use the optimized `lodash.debounce` package that is also available with the Codesandbox configuration.
=> fix(combobox): codesandbox debounce imports

content/figma/assets.yml
Adds new node IDs for save pattern page to fix the build.
=> fix: use updated node IDs in save pattern assets

plugins/gatsby-source-garden-content/utils.ts
Fixes #580 (for full context of the root issue being solved)
Splits the `v1/images` API call into smaller chunks to prevent timeout errors.
Figma's REST API has a tendency to timeout if you request too many node IDs on their `v1/images` endpoint.
Their recommendation is to do multiple small requests to ensure all assets are returned quickly without hitting the timeout.
In our code, the solution then is to chunk the node ID list into a few small batches and run a fetch request on each, then merge the responses. Since `fetch` is async, a `for await` loop is leveraged to safely resolve each request sequentially.
=> fix(build): split figma v1/images API calls into chunks

eslint.config.mjs, package-lock.json, package.json, src/components/MarkdownProvider/components/Alert.tsx, src/components/MarkdownProvider/components/CodeExample/index.tsx, src/components/MarkdownProvider/components/ColorPalette.tsx, src/components/MarkdownProvider/components/Component.tsx, src/components/MarkdownProvider/components/Configuration.tsx, src/components/MarkdownProvider/components/OverviewLinks.tsx, src/components/MarkdownProvider/components/PropSheet.tsx, src/examples/chrome/ChromeNavigation.tsx, src/examples/chrome/GlobalAlert.tsx, src/examples/design/icons/SvgSearch.tsx, src/examples/draggable/DropzoneDanger.tsx, src/examples/draggable/DropzoneDefault.tsx, src/examples/forms/checkbox/Indeterminate.tsx, src/examples/modal/ModalDanger.tsx, src/examples/modal/ModalDefault.tsx, src/examples/modal/ModalSize.tsx, src/layouts/Root/components/Header.tsx, src/layouts/Root/index.tsx, src/layouts/Sidebar/components/DesktopSidebar.tsx, src/layouts/Sidebar/components/MobileSidebar.tsx, src/layouts/Sidebar/index.tsx, src/layouts/Titled/components/TOC.tsx, src/layouts/Titled/index.tsx, utils/typings/styled.d.ts
Restores a set of `@typescript-eslint` rules lost in #585 and honors the addition of `react/jsx-no-leaked-render` added to the latest underlying config. The majority of file updates include the `!!` boolean coercion recommended by the [no-leaked-render rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md).
=> fix: eslint configuration

package-lock.json, package.json, src/examples/tooltip/TooltipDefault.tsx, src/examples/tooltip/TooltipPlacement.tsx, src/examples/tooltip/TooltipSize.tsx, src/examples/tooltip/TooltipType.tsx
Updates `react-tooltips` docs examples. Didn't see any areas where Tooltip was used in the website as a whole that needed updating.
=> feat(components): update tooltips to v9

src/pages/components/combobox.mdx, src/pages/components/menu.mdx
Adds new sections to Menu and Combobox API docs about JSX requirements to help address repeated pitfalls in component composition.
=> chore: expands menu and combobox JSX API documentation

package-lock.json, package.json, src/examples/date-picker/DatePickerCustom.tsx, src/examples/date-picker/DatePickerDefault.tsx, src/examples/date-picker/DatePickerLocalization.tsx, src/examples/date-picker/DatePickerRange.tsx, src/examples/date-picker/DatePickerSize.tsx, src/examples/date-picker/DatePickerTimeWindow.tsx
Completed in previous PRs:
- Update submodule paths
- Updates MDX content per migration changes
=> feat(components): update datepickers to v9

src/pages/components/combobox.mdx, src/pages/components/menu.mdx
Pulls in recent docs update from `main` (#606).
=> chore: sync main changes to next

src/examples/notifications/alerts/AlertDefault.tsx, src/examples/notifications/alerts/AlertType.tsx, src/examples/notifications/notifications/NotificationDefault.tsx, src/examples/notifications/notifications/NotificationPlacement.tsx, src/examples/notifications/notifications/NotificationType.tsx, src/examples/notifications/well/WellDefault.tsx, src/examples/notifications/well/WellFloating.tsx, src/examples/notifications/well/WellMultiline.tsx, src/examples/notifications/well/WellRecessed.tsx, src/pages/components/well.mdx
=> feat(components): update notifications to v9

plugins/gatsby-source-garden-content/utils.ts
🚧 🔧 Tinkering with Figma fetch requests to fix another suite of failing builds
=> fix(build): reduce figma fetch size

package-lock.json, package.json, src/examples/pagination/OffsetDefault.tsx, src/examples/pagination/OffsetGap.tsx, src/examples/pagination/OffsetPadding.tsx, src/examples/table/TablePagination.tsx, src/pages/components/pagination.mdx
=> feat(components): updates pagination to v9

package-lock.json, package.json, src/examples/drawer/DrawerDefault.tsx, src/examples/modal/ModalDanger.tsx, src/examples/modal/ModalDefault.tsx, src/examples/modal/ModalSize.tsx, src/examples/tooltip-modal/TooltipModalDefault.tsx, src/examples/tooltip-modal/TooltipModalPlacement.tsx
Updates `react-tables` to v9.
- Refactors examples to use `Table`'s subComponent properties
- [] ~~MDX - Update docs to reflect migration changes~~
=> feat(components): update `modals` to v9

package-lock.json, package.json, src/examples/chrome/ChromeDefault.tsx, src/examples/chrome/ChromeNavigation.tsx, src/examples/chrome/ChromeStandaloneHeader.tsx, src/examples/chrome/GlobalAlert.tsx, src/examples/chrome/SheetDefault.tsx, src/examples/chrome/SheetFooters.tsx, src/examples/chrome/SheetHeaders.tsx, src/examples/chrome/SheetPlacement.tsx, src/examples/chrome/SheetSize.tsx, src/pages/components/sheet.mdx
=> feat(components): update `chrome` to v9

src/examples/date-picker/DatePickerRange.tsx, src/examples/date-picker/DatePickerTimeWindow.tsx, src/examples/design/icons/IconShowcase.tsx, src/examples/design/icons/IconStyles.tsx, src/examples/design/icons/SvgSearch.tsx, src/examples/theme-provider/ThemeProviderBranding.tsx, src/examples/theme-provider/ThemeProviderDefault.tsx, src/examples/theme-provider/ThemeProviderExtension.tsx, src/examples/theme-provider/ThemeProviderNesting.tsx, src/examples/utilities/MenuArrowStyles.tsx, src/pages/404.tsx
Running ESLint with the `eslint-plugin-deprecation` plugin revealed instances of deprecated subComponent exports.
=> refactor: migrate deprecated subComponent exports to subComponent properties

src/examples/combobox/MultiselectTags.tsx
Same fix as https://github.com/zendeskgarden/react-components/pull/1983
=> fix: allow custom multiselect tags to truncate
